# Gradle Properties
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Mod Properties
version=3.0.20-beta.1
maven_group=io.github.axolotlclient
archives_base_name=AxolotlClientConfig

# Minecraft versions
minecraft_18=1.8.9
minecraft_cts8=1.16_combat-6
minecraft_120=1.20.1
minecraft_121=1.21.1

# Mappings versions
mappings_18=1.8.9+build.28
mappings_cts8=1.16_combat-6+build.2
mappings_120=1.20.1+build.23
mappings_121=1.21.1+build.3

# Loader versions
fabric_loader=0.17.2

# Library versions
fapi_120=0.92.2
fapi_121=0.102.0
fabric_cts8=0.42.0+1.16
osl=0.16.3
legacy_lwjgl3=1.2.9
