pluginManagement {
	repositories {
		// Currently needed for Intermediary and other temporary dependencies
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		maven {
			name = 'Ornithe Releases'
			url = 'https://maven.ornithemc.net/releases'
		}
		maven {
			name = 'Ornithe Snapshots'
			url = 'https://maven.ornithemc.net/snapshots'
		}
		gradlePluginPortal()
	}
}

include 'common'
include '1.8.9-vanilla'
include '1.20-vanilla'
include '1.21-vanilla'
include '1.latest-vanilla'
include 'common-rounded'
include '1.8.9-rounded'
include '1.20-rounded'
include '1.21-rounded'
include '1.latest-rounded'
