pluginManagement {
	repositories {
		// Currently needed for Intermediary and other temporary dependencies
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		maven {
			name = 'Ornithe Releases'
			url = 'https://maven.ornithemc.net/releases'
		}
		maven {
			name = 'Ornithe Snapshots'
			url = 'https://maven.ornithemc.net/snapshots'
		}
		gradlePluginPortal()
	}
}

include 'common'
include '1.8.9'
include '1.16_combat-6'
include '1.20'
include '1.21'
include '1.21.7'
